# Generated by Django 5.1.5 on 2025-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default=1, max_length=20, verbose_name='작성자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(null=True, verbose_name='마감일자'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_complete',
            field=models.BooleanField(choices=[(True, '완료'), (False, '미완료')], default=False, verbose_name='완료여부'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일자'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(null=True, verbose_name='시작일자'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
